[technote]
id = "DMTN-283"
series_id = "DMTN"
canonical_url = "https://dmtn-283.lsst.io"
github_url = "https://github.com/lsst-dm/dmtn-283"
github_default_branch = "main"
date_created = 2024-02-19T17:33:43Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
internal_id = "jennesst"
orcid = "https://orcid.org/0000-0001-5982-167X"
name = {given = "Tim", family = "Jenness"}
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
[[technote.authors]]
name = {given = "David H.", family = "Irving"}
internal_id = "irvingd"
orcid = "https://orcid.org/0009-0005-9099-4970"
[[technote.authors.affiliations]]
name = "Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory/NSF NOIRLab"
internal_id = "RubinOps"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
